# Generated by Django 2.0.2 on 2018-02-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladybugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='user_id',
            field=models.ForeignKey(default=5, max_length=50, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
