# Generated by Django 2.0.2 on 2018-02-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ladybugs', '0002_recipes_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(max_length=150, to='ladybugs.Ingredients'),
        ),
    ]
