# Generated by Django 2.0.2 on 2018-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybugs', '0003_auto_20180208_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
