# Generated by Django 2.0.2 on 2018-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladybugs', '0006_auto_20180214_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(max_length=150, through='ladybugs.RecipesInside', to='ladybugs.Ingredients'),
        ),
    ]
